version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/v2.api.aftaa.ru
      - ./docker/nginx/hosts:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    restart: always
    links:
      - php

  php:
    build: ./docker/php
    volumes:
      - .:/var/www/v2.api.aftaa.ru
    restart: always
    links:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - "3385:3385"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3385
    restart: always
